package com.example.xm.xianyc.utils;

public class StringConst {
    public static String phone_url=
            "https://market.m.taobao.com/app/idleFish-F2e/widle-taobao-rax/page-detail?wh_weex=true&wx_navbar_transparent=true&id=";
    public static String key_word="";
    public static String max_price="";
    public static String min_price="";
    public static String url_market="";
    public static String desc="";
    public static String img_url="";
    public static String region = "";
    public static String tmp2="Sri Lanka:-1,74:LK:Asia/Colombo:\\r\\n" +
           "Sri Lanka Standard Time:-1,74:LK:Asia/Colombo:\\r\\n" +
           "Beijing:-1,75::Asia/Shanghai:\\r\\n" +
            "China:-1,75::Asia/Shanghai:\\r\\n" +
            "China Standard Time:-1,75::Asia/Shanghai:\\r\\n" +
           "AUS Central:-1,76::Australia/Darwin:\\r\\n" +
            "AUS Central Standard Time:-1,76::Australia/Darwin:\\r\\n" +
            "Cen. Australia:-1,76::Australia/Adelaide:\\r\\n" +
            "Cen. Australia Standard Time:-1,76::Australia/Adelaide:\\r\\n" +
           "Vladivostok:-1,77::Asia/Vladivostok:\\r\\n" +
           "Vladivostok Standard Time:-1,77::Asia/Vladivostok:\\r\\n" +
            "West Pacific:-1,77:GU:Pacific/Guam:\\r\\n" +
           "West Pacific Standard Time:-1,77:GU:Pacific/Guam:\\r\\n" +
           "E. South America:-1,80::America/Sao_Paulo:\\r\\n" +
           "E. South America Standard Time:-1,80::America/Sao_Paulo:\\r\\n" +
            "Greenland Standard Time:-1,80:GL:America/Godthab:\\r\\n" +
           "Newfoundland:-1,81::America/St_Johns:\\r\\n " +
            "Newfoundland Standard Time:-1,81::America/St_Johns:\\r\\n ";
    public static String temp = "#0\r\n" +
            "# This file describes mapping information between Windows and Java\r\n" +
            "# time zones.\r\n" +
            "# Format: Each line should include a colon separated fields of Windows\r\n" +
            "# time zone registry key, time zone mapID, locale (which is most\r\n" +
            "# likely used in the time zone), and Java time zone ID. Blank lines\r\n" +
            "# and lines that start with '#' are ignored. Data lines must be sorted\r\n" +
            "# by mapID (ASCII order).\r\n" +
            "#\r\n" +
            "#                            NOTE\r\n" +
            "# This table format is not a public interface of any Java\r\n" +
            "# platforms. No applications should depend on this file in any form.\r\n" +
            "#\r\n" +
            "# This table has been generated by a program and should not be edited\r\n" +
            "# manually.\r\n" +
            "#\r\n" +
            "Romance:-1,64::Europe/Paris:\r\n" +
            "Romance Standard Time:-1,64::Europe/Paris:\r\n" +
            "Warsaw:-1,65::Europe/Warsaw:\r\n" +
            "Central Europe:-1,66::Europe/Prague:\r\n" +
            "Central Europe Standard Time:-1,66::Europe/Prague:\r\n" +
            "Prague Bratislava:-1,66::Europe/Prague:\r\n" +
            "W. Central Africa Standard Time:-1,66:AO:Africa/Luanda:\r\n" +
            "FLE:-1,67:FI:Europe/Helsinki:\r\n" +
            "FLE Standard Time:-1,67:FI:Europe/Helsinki:\r\n" +
            "GFT:-1,67::Europe/Athens:\r\n" +
            "GFT Standard Time:-1,67::Europe/Athens:\r\n" +
            "GTB:-1,67::Europe/Athens:\r\n" +
            "GTB Standard Time:-1,67::Europe/Athens:\r\n" +
            "Israel:-1,70::Asia/Jerusalem:\r\n" +
            "Israel Standard Time:-1,70::Asia/Jerusalem:\r\n" +
            "Arab:-1,71::Asia/Riyadh:\r\n" +
            "Arab Standard Time:-1,71::Asia/Riyadh:\r\n" +
            "Arabic Standard Time:-1,71:IQ:Asia/Baghdad:\r\n" +
            "E. Africa:-1,71:KE:Africa/Nairobi:\r\n" +
            "E. Africa Standard Time:-1,71:KE:Africa/Nairobi:\r\n" +
            "Saudi Arabia:-1,71::Asia/Riyadh:\r\n" +
            "Saudi Arabia Standard Time:-1,71::Asia/Riyadh:\r\n" +
            "Iran:-1,72::Asia/Tehran:\r\n" +
            "Iran Standard Time:-1,72::Asia/Tehran:\r\n" +
            "Afghanistan:-1,73::Asia/Kabul:\r\n" +
            "Afghanistan Standard Time:-1,73::Asia/Kabul:\r\n" +
            "India:-1,74::Asia/Calcutta:\r\n" +
            "India Standard Time:-1,74::Asia/Calcutta:\r\n" +
            "Myanmar Standard Time:-1,74::Asia/Rangoon:\r\n" +
            "Nepal Standard Time:-1,74::Asia/Katmandu:\r\n" +
            "Sri Lanka:-1,74:LK:Asia/Colombo:\r\n" +
            "Sri Lanka Standard Time:-1,74:LK:Asia/Colombo:\r\n" +
            "Beijing:-1,75::Asia/Shanghai:\r\n" +
            "China:-1,75::Asia/Shanghai:\r\n" +
            "China Standard Time:-1,75::Asia/Shanghai:\r\n" +
            "AUS Central:-1,76::Australia/Darwin:\r\n" +
            "AUS Central Standard Time:-1,76::Australia/Darwin:\r\n" +
            "Cen. Australia:-1,76::Australia/Adelaide:\r\n" +
            "Cen. Australia Standard Time:-1,76::Australia/Adelaide:\r\n" +
            "Vladivostok:-1,77::Asia/Vladivostok:\r\n" +
            "Vladivostok Standard Time:-1,77::Asia/Vladivostok:\r\n" +
            "West Pacific:-1,77:GU:Pacific/Guam:\r\n" +
            "West Pacific Standard Time:-1,77:GU:Pacific/Guam:\r\n" +
            "E. South America:-1,80::America/Sao_Paulo:\r\n" +
            "E. South America Standard Time:-1,80::America/Sao_Paulo:\r\n" +
            "Greenland Standard Time:-1,80:GL:America/Godthab:\r\n" +
            "Newfoundland:-1,81::America/St_Johns:\r\n" +
            "Newfoundland Standard Time:-1,81::America/St_Johns:\r\n" +
            "Pacific SA:-1,82::America/Santiago:\r\n" +
            "Pacific SA Standard Time:-1,82::America/Santiago:\r\n" +
            "SA Western:-1,82:BO:America/La_Paz:\r\n" +
            "SA Western Standard Time:-1,82:BO:America/La_Paz:\r\n" +
            "SA Pacific:-1,83::America/Bogota:\r\n" +
            "SA Pacific Standard Time:-1,83::America/Bogota:\r\n" +
            "US Eastern:-1,84::America/Indianapolis:\r\n" +
            "US Eastern Standard Time:-1,84::America/Indianapolis:\r\n" +
            "Central America Standard Time:-1,85::America/Regina:\r\n" +
            "Mexico:-1,85::America/Mexico_City:\r\n" +
            "Mexico Standard Time:-1,85::America/Mexico_City:\r\n" +
            "Canada Central:-1,86::America/Regina:\r\n" +
            "Canada Central Standard Time:-1,86::America/Regina:\r\n" +
            "US Mountain:-1,87::America/Phoenix:\r\n" +
            "US Mountain Standard Time:-1,87::America/Phoenix:\r\n" +
            "GMT:0,1::Europe/London:\r\n" +
            "GMT Standard Time:0,1::Europe/London:\r\n" +
            "Ekaterinburg:10,11::Asia/Yekaterinburg:\r\n" +
            "Ekaterinburg Standard Time:10,11::Asia/Yekaterinburg:\r\n" +
            "West Asia:10,11:UZ:Asia/Tashkent:\r\n" +
            "West Asia Standard Time:10,11:UZ:Asia/Tashkent:\r\n" +
            "Central Asia:12,13::Asia/Almaty:\r\n" +
            "Central Asia Standard Time:12,13::Asia/Almaty:\r\n" +
            "N. Central Asia Standard Time:12,13::Asia/Novosibirsk:\r\n" +
            "Bangkok:14,15::Asia/Bangkok:\r\n" +
            "Bangkok Standard Time:14,15::Asia/Bangkok:\r\n" +
            "North Asia Standard Time:14,15::Asia/Krasnoyarsk:\r\n" +
            "SE Asia:14,15::Asia/Bangkok:\r\n" +
            "SE Asia Standard Time:14,15::Asia/Bangkok:\r\n" +
            "North Asia East Standard Time:16,17:RU:Asia/Irkutsk:\r\n" +
            "Singapore:16,17:SG:Asia/Singapore:\r\n" +
            "Singapore Standard Time:16,17:SG:Asia/Singapore:\r\n" +
            "Taipei:16,17::Asia/Taipei:\r\n" +
            "Taipei Standard Time:16,17::Asia/Taipei:\r\n" +
            "W. Australia:16,17:AU:Australia/Perth:\r\n" +
            "W. Australia Standard Time:16,17:AU:Australia/Perth:\r\n" +
            "Korea:18,19:KR:Asia/Seoul:\r\n" +
            "Korea Standard Time:18,19:KR:Asia/Seoul:\r\n" +
            "Tokyo:18,19::Asia/Tokyo:\r\n" +
            "Tokyo Standard Time:18,19::Asia/Tokyo:\r\n" +
            "Yakutsk:18,19:RU:Asia/Yakutsk:\r\n" +
            "Yakutsk Standard Time:18,19:RU:Asia/Yakutsk:\r\n" +
            "Central European:2,3:CS:Europe/Belgrade:\r\n" +
            "Central European Standard Time:2,3:CS:Europe/Belgrade:\r\n" +
            "W. Europe:2,3::Europe/Berlin:\r\n" +
            "W. Europe Standard Time:2,3::Europe/Berlin:\r\n" +
            "Tasmania:20,-1::Australia/Hobart:\r\n" +
            "Tasmania Standard Time:20,-1::Australia/Hobart:\r\n" +
            "AUS Eastern:20,21::Australia/Sydney:\r\n" +
            "AUS Eastern Standard Time:20,21::Australia/Sydney:\r\n" +
            "E. Australia:20,21::Australia/Brisbane:\r\n" +
            "E. Australia Standard Time:20,21::Australia/Brisbane:\r\n" +
            "Sydney Standard Time:20,21::Australia/Sydney:\r\n" +
            "Tasmania Standard Time:20,65::Australia/Hobart:\r\n" +
            "Central Pacific:22,23::Pacific/Guadalcanal:\r\n" +
            "Central Pacific Standard Time:22,23::Pacific/Guadalcanal:\r\n" +
            "Dateline:24,25::GMT-1200:\r\n" +
            "Dateline Standard Time:24,25::GMT-1200:\r\n" +
            "Fiji:24,25::Pacific/Fiji:\r\n" +
            "Fiji Standard Time:24,25::Pacific/Fiji:\r\n" +
            "Samoa:26,27::Pacific/Apia:\r\n" +
            "Samoa Standard Time:26,27::Pacific/Apia:\r\n" +
            "Hawaiian:28,29::Pacific/Honolulu:\r\n" +
            "Hawaiian Standard Time:28,29::Pacific/Honolulu:\r\n" +
            "Alaskan:30,31::America/Anchorage:\r\n" +
            "Alaskan Standard Time:30,31::America/Anchorage:\r\n" +
            "Pacific:32,33::America/Los_Angeles:\r\n" +
            "Pacific Standard Time:32,33::America/Los_Angeles:\r\n" +
            "Mexico Standard Time 2:34,35:MX:America/Chihuahua:\r\n" +
            "Mountain:34,35::America/Denver:\r\n" +
            "Mountain Standard Time:34,35::America/Denver:\r\n" +
            "Central:36,37::America/Chicago:\r\n" +
            "Central Standard Time:36,37::America/Chicago:\r\n" +
            "Eastern:38,39::America/New_York:\r\n" +
            "Eastern Standard Time:38,39::America/New_York:\r\n" +
            "E. Europe:4,5:BY:Europe/Minsk:\r\n" +
            "E. Europe Standard Time:4,5:BY:Europe/Minsk:\r\n" +
            "Egypt:4,68::Africa/Cairo:\r\n" +
            "Egypt Standard Time:4,68::Africa/Cairo:\r\n" +
            "South Africa:4,69::Africa/Harare:\r\n" +
            "South Africa Standard Time:4,69::Africa/Harare:\r\n" +
            "Atlantic:40,41::America/Halifax:\r\n" +
            "Atlantic Standard Time:40,41::America/Halifax:\r\n" +
            "SA Eastern:42,43:GF:America/Cayenne:\r\n" +
            "SA Eastern Standard Time:42,43:GF:America/Cayenne:\r\n" +
            "Mid-Atlantic:44,45::Atlantic/South_Georgia:\r\n" +
            "Mid-Atlantic Standard Time:44,45::Atlantic/South_Georgia:\r\n" +
            "Azores:46,47::Atlantic/Azores:\r\n" +
            "Azores Standard Time:46,47::Atlantic/Azores:\r\n" +
            "Cape Verde Standard Time:46,47::Atlantic/Cape_Verde:\r\n" +
            "Russian:6,7::Europe/Moscow:\r\n" +
            "Russian Standard Time:6,7::Europe/Moscow:\r\n" +
            "New Zealand:78,79::Pacific/Auckland:\r\n" +
            "New Zealand Standard Time:78,79::Pacific/Auckland:\r\n" +
            "Tonga Standard Time:78,79::Pacific/Tongatapu:\r\n" +
            "Arabian:8,9::Asia/Muscat:\r\n" +
            "Arabian Standard Time:8,9::Asia/Muscat:\r\n" +
            "Caucasus:8,9:AM:Asia/Yerevan:\r\n" +
            "Caucasus Standard Time:8,9:AM:Asia/Yerevan:\r\n" +
            "GMT Standard Time:88,89::GMT:\r\n" +
            "Greenwich:88,89::GMT:\r\n" +
            "Greenwich Standard Time:88,89::GMT:\r\n" +
            "Argentina Standard Time:900,900::America/Buenos_Aires:\r\n" +
            "Azerbaijan Standard Time:901,901:AZ:Asia/Baku:\r\n" +
            "Bangladesh Standard Time:902,902::Asia/Dhaka:\r\n" +
            "Central Brazilian Standard Time:903,903:BR:America/Cuiaba:\r\n" +
            "Central Standard Time (Mexico):904,904::America/Mexico_City:\r\n" +
            "Georgian Standard Time:905,905:GE:Asia/Tbilisi:\r\n" +
            "Jordan Standard Time:906,906:JO:Asia/Amman:\r\n" +
            "Kamchatka Standard Time:907,907:RU:Asia/Kamchatka:\r\n" +
            "Mauritius Standard Time:908,908:MU:Indian/Mauritius:\r\n" +
            "Middle East Standard Time:909,909:LB:Asia/Beirut:\r\n" +
            "Montevideo Standard Time:910,910:UY:America/Montevideo:\r\n" +
            "Morocco Standard Time:911,911:MA:Africa/Casablanca:\r\n" +
            "Mountain Standard Time (Mexico):912,912:MX:America/Chihuahua:\r\n" +
            "Namibia Standard Time:913,913:NA:Africa/Windhoek:\r\n" +
            "Pacific Standard Time (Mexico):914,914:MX:America/Tijuana:\r\n" +
            "Pakistan Standard Time:915,915::Asia/Karachi:\r\n" +
            "Paraguay Standard Time:916,916:PY:America/Asuncion:\r\n" +
            "Syria Standard Time:917,917:SY:Asia/Damascus:\r\n" +
            "UTC:918,918::UTC:\r\n" +
            "UTC+12:919,919::GMT+1200:\r\n" +
            "UTC-02:920,920::GMT-0200:\r\n" +
            "UTC-11:921,921::GMT-1100:\r\n" +
            "Ulaanbaatar Standard Time:922,922::Asia/Ulaanbaatar:\r\n" +
            "Venezuela Standard Time:923,923::America/Caracas:\r\n" +
            "Magadan Standard Time:924,924::Asia/Magadan:\r\n" +
            "Kaliningrad Standard Time:925,925:RU:Europe/Kaliningrad:\r\n" +
            "Turkey Standard Time:926,926::Asia/Istanbul:\r\n" +
            "Bahia Standard Time:927,927::America/Bahia:\r\n" +
            "Western Brazilian Standard Time:928,928:BR:America/Rio_Branco:\r\n" +
            "Armenian Standard Time:929,929:AM:Asia/Yerevan:\r\n" +
            "null\r\n";
}
